openapi: 3.0.3
info:
  title: Stelling example internal API
  version: 0.1.0

servers:
  - url: /internal

paths:
  /healthz:
    get:
      operationId: healthz
      summary: Simple ping healthcheck
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/healthz-response"

components:
  schemas:
    healthz-response:
      type: object
      required: [message]
      properties:
        message:
          type: string
