// Package types provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package types

// ErrorResponse RFC 9457 Problem Details error response
type ErrorResponse struct {
	// Detail A highly contextual, readable explanation breaking down explicitly what triggered this error scenario.
	Detail string `json:"detail"`
	Status int    `json:"status"`

	// Title A brief summary defining the class of failure, optimal for quick user interface groupings.
	Title string `json:"title"`

	// Type An absolute or relative URI reference pointing to human-readable documentation concerning the specific problem type encountered.
	Type string `json:"type"`
}
