version: 2
registries:
  github:
    type: git
    url: https://github.com
    username: x-access-token
    password: ${{ secrets.GH_TOKEN }}
updates:
- package-ecosystem: gomod
  registries:
  - github
  directory: /blobd
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  groups:
    all:
      patterns:
        - "*"
- package-ecosystem: "github-actions"
  directory: /
  schedule:
    interval: weekly
  groups:
    all:
      patterns:
        - "*"
