version: "2"
linters:
  enable:
    - govet
    - bodyclose
    - durationcheck
    - errname
    - goprintffuncname
    - grouper
    - makezero
    - misspell
    - nilerr
    - noctx
    - nosprintfhostport
    - promlinter
    - rowserrcheck
    - sqlclosecheck
    - thelper
    - unconvert
    - unparam
    - wastedassign
  settings:
    staticcheck:
      checks:
        - all
        - -QF1008 # Allow using name of embedded field in selector
        - -ST1000
        - -ST1003
        - -ST1016
        - -ST1020
        - -ST1021
        - -ST1022
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
