services:
  http-server:
    build:
      context: .
      target: deploy
    environment:
      - CONFIG_GREETING_MESSAGE="hello from docker compose"
      - CONFIG_HTTP_SERVER_ADDRESS=0.0.0.0:8080
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "wget", "-q", "-O", "-", "http://localhost:8080/internal/healthz"]
      interval: 10s
      timeout: 5s
      retries: 3

  grpc-server:
    build:
      context: .
      target: deploy
    command: ["/app/grpc-server"]
    environment:
      - CONFIG_GREETING_MESSAGE="hello from grpc docker compose"
      - CONFIG_SERVER_ADDRESS=0.0.0.0:8081
    ports:
      - "8081:8081"
