VERSION --try 0.8

ARG --global EXOSCALE_DOCKER_REGISTRY=registry.internal.exoscale.ch
ARG --global GO_VERSION=1.26.5

# --- Base images ---
deps:
    FROM ${EXOSCALE_DOCKER_REGISTRY}/docker.io/library/golang:${GO_VERSION}-alpine
    WORKDIR /build
    COPY go.mod go.sum ./
    RUN go mod download
    RUN go install github.com/golangci/golangci-lint/v2/cmd/golangci-lint@latest
    RUN go install github.com/oapi-codegen/oapi-codegen/v2/cmd/oapi-codegen@latest

source:
    FROM +deps
    COPY . .

# --- Codegen ---

# Generates code from OpenAPI specs and updates local files
gen-oapi:
    FROM +source
    RUN oapi-codegen -config api/public/cfg.yaml api/public/api.yaml
	RUN oapi-codegen -config api/internal/cfg.yaml api/internal/api.yaml
    SAVE ARTIFACT api/public/api.gen.go AS LOCAL api/public/api.gen.go
    SAVE ARTIFACT api/internal/api.gen.go AS LOCAL api/internal/api.gen.go

# Generates code from protobuf spec and updates local files
gen-proto:
    FROM ${EXOSCALE_DOCKER_REGISTRY}/docker.io/bufbuild/buf:1
    WORKDIR /app
    COPY proto proto
	RUN buf generate proto --template proto/buf.gen.yaml -o proto
    SAVE ARTIFACT proto/schema.pb.go AS LOCAL proto/schema.pb.go
    SAVE ARTIFACT proto/schema_grpc.pb.go AS LOCAL proto/schema_grpc.pb.go

# --- Quality ---

# Formatting check that simply fails if not formatted correctly
format:
    FROM +source
    RUN unformatted="$(gofmt -l . | grep -v '^vendor/')"; test -z "$unformatted" || (echo "$unformatted" && exit 1)

# Lint check that will simply fail if linting fails
lint:
    FROM +source
    RUN golangci-lint run ./...

# Formatting and lint fixes, applied to the local filesystem
format-lint-fix:
    FROM +source
    RUN golangci-lint fmt ./...
    RUN golangci-lint run --fix ./...
    RUN rm -rf ./.tmp-* # Remove temporary dirs
    SAVE ARTIFACT ./* AS LOCAL .

vulncheck:
    FROM +source
    RUN go install golang.org/x/vuln/cmd/govulncheck@latest
    RUN govulncheck ./...

buf-lint:
    FROM ${EXOSCALE_DOCKER_REGISTRY}/docker.io/bufbuild/buf:1
    WORKDIR /app
    COPY proto proto
	RUN buf lint proto

# --- Testing ---

test:
    FROM +source
    RUN go test ./...

# --- Image builds ---

build:
    FROM +source
    ARG --required NAME
    RUN CGO_ENABLED=0 go build -o /app/${NAME} ./cmd/${NAME}
    SAVE ARTIFACT /app/${NAME}

deploy:
    FROM ${EXOSCALE_DOCKER_REGISTRY}/docker.io/library/alpine:3.24
    ARG --required NAME
    ARG --required TAGS
    COPY (+build/${NAME} --NAME=${NAME}) /app/${NAME}

    USER 65534
    CMD ["/app/${NAME}"]

    FOR TAG IN $TAGS
        SAVE IMAGE --push ${EXOSCALE_DOCKER_REGISTRY}/exoscale/stelling/${NAME}:${TAG}
    END

# --- CI pipeline ---

# Full CI pipeline which runs checks, then builds images.
pipeline-ci:
    ARG TAGS=dev
    WAIT
        BUILD +format
        BUILD +lint
        BUILD +test
        BUILD +buf-lint
    END
    BUILD +deploy --NAME=grpc-server --TAGS=${TAGS}
    BUILD +deploy --NAME=http-server --TAGS=${TAGS}
    BUILD +deploy --NAME=job --TAGS=${TAGS}
