VERSION --try 0.8

ARG --global EXOSCALE_DOCKER_REGISTRY=registry.internal.exoscale.ch
ARG --global GO_VERSION=1.26.5

# --- Base images ---
source:
    FROM library/golang:${GO_VERSION}-alpine
    WORKDIR /build
    RUN go install github.com/golangci/golangci-lint/v2/cmd/golangci-lint@latest
    COPY go.mod go.sum ./
    COPY . .

# --- Quality ---

# Formatting and lint fixes, applied to the local filesystem
format:
    FROM +source
    RUN golangci-lint fmt ./...
    RUN golangci-lint run --fix ./...
    RUN rm -rf ./.tmp-* # Remove temporary dirs
    SAVE ARTIFACT ./* AS LOCAL .

vulncheck:
    FROM +source
    RUN go install golang.org/x/vuln/cmd/govulncheck@latest
    RUN govulncheck ./...

# --- Testing ---

test:
    FROM +source
    RUN go test ./...

# --- Image build and push ---

build:
    FROM +source
    ARG --required NAME
    # Inject standard stelling variable to expose versions as metrics
    LET revisionOpt="-X 'github.com/exoscale/stelling/fxmetrics.revision=${EARTHLY_GIT_HASH}'"
    LET revisionTimestampOpt="-X 'github.com/exoscale/stelling/fxmetrics.revisionTimestamp=${EARTHLY_GIT_COMMIT_TIMESTAMP}'"
    RUN CGO_ENABLED=0 go build -ldflags="${revisionOpt} ${revisionTimestampOpt}" -o /app/run ./cmd/${NAME}
    SAVE ARTIFACT /app/run

oci-image-build-jobs:
    FROM library/alpine:3.24
    COPY (+build/run --NAME="job") /app/job
    USER 65534
    CMD ["/app/job"]
    ARG TAGS=dev
    FOR TAG IN $TAGS
    END

oci-image-build-grpc-server:
    FROM library/alpine:3.24
    COPY (+build/run --NAME="server") /app/server
    USER 65534
    CMD ["/app/grpc-server"]
    ARG TAGS=dev
    FOR TAG IN $TAGS
    END

oci-image-build-http-server:
    FROM library/alpine:3.24
    COPY (+build/run --NAME="http-server") /app/http-server
    USER 65534
    CMD ["/app/http-server"]
    ARG TAGS=dev
    FOR TAG IN $TAGS
    END

oci-images:
    BUILD +oci-image-build-jobs
    BUILD +oci-image-build-http-server
    BUILD +oci-image-build-grpc-server


# --- CI pipeline ---

ci:
    BUILD +format
    BUILD +test
    BUILD +oci-images
