// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: schema.proto

package schema

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TLS struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Version      uint64                 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	SerialNumber uint64                 `protobuf:"varint,2,opt,name=serial_number,json=serialNumber,proto3" json:"serial_number,omitempty"`
	Issuer       *TLSName               `protobuf:"bytes,3,opt,name=issuer,proto3" json:"issuer,omitempty"`
	Subject      *TLSName               `protobuf:"bytes,4,opt,name=subject,proto3" json:"subject,omitempty"`
	NotBefore    *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=not_before,json=notBefore,proto3" json:"not_before,omitempty"`
	NotAfter     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=not_after,json=notAfter,proto3" json:"not_after,omitempty"`
	IsCa         bool                   `protobuf:"varint,7,opt,name=is_ca,json=isCa,proto3" json:"is_ca,omitempty"`
	// SAN values
	DnsNames       []string `protobuf:"bytes,8,rep,name=dns_names,json=dnsNames,proto3" json:"dns_names,omitempty"`
	EmailAddresses []string `protobuf:"bytes,9,rep,name=email_addresses,json=emailAddresses,proto3" json:"email_addresses,omitempty"`
	IpAddresses    []string `protobuf:"bytes,10,rep,name=ip_addresses,json=ipAddresses,proto3" json:"ip_addresses,omitempty"`
	Uris           []string `protobuf:"bytes,11,rep,name=uris,proto3" json:"uris,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TLS) Reset() {
	*x = TLS{}
	mi := &file_schema_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TLS) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TLS) ProtoMessage() {}

func (x *TLS) ProtoReflect() protoreflect.Message {
	mi := &file_schema_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TLS.ProtoReflect.Descriptor instead.
func (*TLS) Descriptor() ([]byte, []int) {
	return file_schema_proto_rawDescGZIP(), []int{0}
}

func (x *TLS) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *TLS) GetSerialNumber() uint64 {
	if x != nil {
		return x.SerialNumber
	}
	return 0
}

func (x *TLS) GetIssuer() *TLSName {
	if x != nil {
		return x.Issuer
	}
	return nil
}

func (x *TLS) GetSubject() *TLSName {
	if x != nil {
		return x.Subject
	}
	return nil
}

func (x *TLS) GetNotBefore() *timestamppb.Timestamp {
	if x != nil {
		return x.NotBefore
	}
	return nil
}

func (x *TLS) GetNotAfter() *timestamppb.Timestamp {
	if x != nil {
		return x.NotAfter
	}
	return nil
}

func (x *TLS) GetIsCa() bool {
	if x != nil {
		return x.IsCa
	}
	return false
}

func (x *TLS) GetDnsNames() []string {
	if x != nil {
		return x.DnsNames
	}
	return nil
}

func (x *TLS) GetEmailAddresses() []string {
	if x != nil {
		return x.EmailAddresses
	}
	return nil
}

func (x *TLS) GetIpAddresses() []string {
	if x != nil {
		return x.IpAddresses
	}
	return nil
}

func (x *TLS) GetUris() []string {
	if x != nil {
		return x.Uris
	}
	return nil
}

type TLSName struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Country            []string               `protobuf:"bytes,1,rep,name=country,proto3" json:"country,omitempty"`
	Organization       []string               `protobuf:"bytes,2,rep,name=organization,proto3" json:"organization,omitempty"`
	OrganizationalUnit []string               `protobuf:"bytes,3,rep,name=organizational_unit,json=organizationalUnit,proto3" json:"organizational_unit,omitempty"`
	Locality           []string               `protobuf:"bytes,4,rep,name=locality,proto3" json:"locality,omitempty"`
	Province           []string               `protobuf:"bytes,5,rep,name=province,proto3" json:"province,omitempty"`
	StreetAddress      []string               `protobuf:"bytes,6,rep,name=street_address,json=streetAddress,proto3" json:"street_address,omitempty"`
	PostalCode         []string               `protobuf:"bytes,7,rep,name=postal_code,json=postalCode,proto3" json:"postal_code,omitempty"`
	SerialNumber       string                 `protobuf:"bytes,8,opt,name=serial_number,json=serialNumber,proto3" json:"serial_number,omitempty"`
	CommonName         string                 `protobuf:"bytes,9,opt,name=common_name,json=commonName,proto3" json:"common_name,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *TLSName) Reset() {
	*x = TLSName{}
	mi := &file_schema_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TLSName) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TLSName) ProtoMessage() {}

func (x *TLSName) ProtoReflect() protoreflect.Message {
	mi := &file_schema_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TLSName.ProtoReflect.Descriptor instead.
func (*TLSName) Descriptor() ([]byte, []int) {
	return file_schema_proto_rawDescGZIP(), []int{1}
}

func (x *TLSName) GetCountry() []string {
	if x != nil {
		return x.Country
	}
	return nil
}

func (x *TLSName) GetOrganization() []string {
	if x != nil {
		return x.Organization
	}
	return nil
}

func (x *TLSName) GetOrganizationalUnit() []string {
	if x != nil {
		return x.OrganizationalUnit
	}
	return nil
}

func (x *TLSName) GetLocality() []string {
	if x != nil {
		return x.Locality
	}
	return nil
}

func (x *TLSName) GetProvince() []string {
	if x != nil {
		return x.Province
	}
	return nil
}

func (x *TLSName) GetStreetAddress() []string {
	if x != nil {
		return x.StreetAddress
	}
	return nil
}

func (x *TLSName) GetPostalCode() []string {
	if x != nil {
		return x.PostalCode
	}
	return nil
}

func (x *TLSName) GetSerialNumber() string {
	if x != nil {
		return x.SerialNumber
	}
	return ""
}

func (x *TLSName) GetCommonName() string {
	if x != nil {
		return x.CommonName
	}
	return ""
}

type JWT struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subject       string                 `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	EmailVerified bool                   `protobuf:"varint,3,opt,name=email_verified,json=emailVerified,proto3" json:"email_verified,omitempty"`
	Groups        []string               `protobuf:"bytes,4,rep,name=groups,proto3" json:"groups,omitempty"`
	Issuer        string                 `protobuf:"bytes,5,opt,name=issuer,proto3" json:"issuer,omitempty"`
	Audience      []string               `protobuf:"bytes,6,rep,name=audience,proto3" json:"audience,omitempty"`
	IssuedAt      *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=issued_at,json=issuedAt,proto3" json:"issued_at,omitempty"`
	Expiry        *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=expiry,proto3" json:"expiry,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JWT) Reset() {
	*x = JWT{}
	mi := &file_schema_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JWT) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JWT) ProtoMessage() {}

func (x *JWT) ProtoReflect() protoreflect.Message {
	mi := &file_schema_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JWT.ProtoReflect.Descriptor instead.
func (*JWT) Descriptor() ([]byte, []int) {
	return file_schema_proto_rawDescGZIP(), []int{2}
}

func (x *JWT) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *JWT) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *JWT) GetEmailVerified() bool {
	if x != nil {
		return x.EmailVerified
	}
	return false
}

func (x *JWT) GetGroups() []string {
	if x != nil {
		return x.Groups
	}
	return nil
}

func (x *JWT) GetIssuer() string {
	if x != nil {
		return x.Issuer
	}
	return ""
}

func (x *JWT) GetAudience() []string {
	if x != nil {
		return x.Audience
	}
	return nil
}

func (x *JWT) GetIssuedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.IssuedAt
	}
	return nil
}

func (x *JWT) GetExpiry() *timestamppb.Timestamp {
	if x != nil {
		return x.Expiry
	}
	return nil
}

type HeaderValues struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         []string               `protobuf:"bytes,1,rep,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeaderValues) Reset() {
	*x = HeaderValues{}
	mi := &file_schema_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeaderValues) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeaderValues) ProtoMessage() {}

func (x *HeaderValues) ProtoReflect() protoreflect.Message {
	mi := &file_schema_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeaderValues.ProtoReflect.Descriptor instead.
func (*HeaderValues) Descriptor() ([]byte, []int) {
	return file_schema_proto_rawDescGZIP(), []int{3}
}

func (x *HeaderValues) GetValue() []string {
	if x != nil {
		return x.Value
	}
	return nil
}

type GrpcRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The GRPC service name: eg grpc.health.v1.Health
	Service string `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	// The method name, eg Check
	Method string `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	// The GRPC request metadata. Key values have been made canonical
	// by golangs net/http.CanonicalHeaderKey
	Headers map[string]*HeaderValues `protobuf:"bytes,3,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// The TLS information. May be absent for non TLS protected requests.
	Tls *TLS `protobuf:"bytes,4,opt,name=tls,proto3" json:"tls,omitempty"`
	// The jwt passed into the request. May be absent.
	Jwt           *JWT `protobuf:"bytes,5,opt,name=jwt,proto3" json:"jwt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GrpcRequest) Reset() {
	*x = GrpcRequest{}
	mi := &file_schema_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrpcRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrpcRequest) ProtoMessage() {}

func (x *GrpcRequest) ProtoReflect() protoreflect.Message {
	mi := &file_schema_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrpcRequest.ProtoReflect.Descriptor instead.
func (*GrpcRequest) Descriptor() ([]byte, []int) {
	return file_schema_proto_rawDescGZIP(), []int{4}
}

func (x *GrpcRequest) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *GrpcRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *GrpcRequest) GetHeaders() map[string]*HeaderValues {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *GrpcRequest) GetTls() *TLS {
	if x != nil {
		return x.Tls
	}
	return nil
}

func (x *GrpcRequest) GetJwt() *JWT {
	if x != nil {
		return x.Jwt
	}
	return nil
}

type HttpRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The HTTP request method, such as `GET`, `POST`
	HttpMethod string `protobuf:"bytes,1,opt,name=http_method,json=httpMethod,proto3" json:"http_method,omitempty"`
	// The HTTP request headers. Header names are made canonical
	// by golangs net/http.CanonicalHeaderKey
	Headers map[string]*HeaderValues `protobuf:"bytes,2,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// The HTTP URL path
	Path string `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	// The HTTP request `Host`
	Host string `protobuf:"bytes,4,opt,name=host,proto3" json:"host,omitempty"`
	// The HTTP URL scheme, such as `http` or `https`
	Scheme string `protobuf:"bytes,5,opt,name=scheme,proto3" json:"scheme,omitempty"`
	// The HTTP URL query in the format of `name1=value1&name2=value2`, as it
	// appears in the first line of the HTTP request. No decoding is performed
	// TODO: maybe decode this for ease of use in the CEL rule?
	Query string `protobuf:"bytes,6,opt,name=query,proto3" json:"query,omitempty"`
	// The HTTP request size in bytes. If unkown, it will be -1
	Size int64 `protobuf:"varint,7,opt,name=size,proto3" json:"size,omitempty"`
	// The network protocol used with the request, such as "http/1.1"
	// "spdy/3", "h2", "h2c", "webrtc", "tcp", "udp", "quick", See
	// https://www.iana.org/assignments/tls-extensiontype-values/tls-extensiontype-values.xhtml#alpn-protocol-ids
	Protocol string `protobuf:"bytes,8,opt,name=protocol,proto3" json:"protocol,omitempty"`
	// The TLS information. May be absent for non TLS protected requests.
	Tls *TLS `protobuf:"bytes,9,opt,name=tls,proto3" json:"tls,omitempty"`
	// The jwt passed into the request. May be absent.
	Jwt *JWT `protobuf:"bytes,10,opt,name=jwt,proto3" json:"jwt,omitempty"`
	// The openapi 'command'. May be absent
	Method        string `protobuf:"bytes,11,opt,name=method,proto3" json:"method,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HttpRequest) Reset() {
	*x = HttpRequest{}
	mi := &file_schema_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HttpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HttpRequest) ProtoMessage() {}

func (x *HttpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_schema_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HttpRequest.ProtoReflect.Descriptor instead.
func (*HttpRequest) Descriptor() ([]byte, []int) {
	return file_schema_proto_rawDescGZIP(), []int{5}
}

func (x *HttpRequest) GetHttpMethod() string {
	if x != nil {
		return x.HttpMethod
	}
	return ""
}

func (x *HttpRequest) GetHeaders() map[string]*HeaderValues {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *HttpRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *HttpRequest) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *HttpRequest) GetScheme() string {
	if x != nil {
		return x.Scheme
	}
	return ""
}

func (x *HttpRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *HttpRequest) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *HttpRequest) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *HttpRequest) GetTls() *TLS {
	if x != nil {
		return x.Tls
	}
	return nil
}

func (x *HttpRequest) GetJwt() *JWT {
	if x != nil {
		return x.Jwt
	}
	return nil
}

func (x *HttpRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

var File_schema_proto protoreflect.FileDescriptor

const file_schema_proto_rawDesc = "" +
	"\n" +
	"\fschema.proto\x12\x1aexoscale.rpc.authorizer.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xc6\x03\n" +
	"\x03TLS\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x04R\aversion\x12#\n" +
	"\rserial_number\x18\x02 \x01(\x04R\fserialNumber\x12;\n" +
	"\x06issuer\x18\x03 \x01(\v2#.exoscale.rpc.authorizer.v1.TLSNameR\x06issuer\x12=\n" +
	"\asubject\x18\x04 \x01(\v2#.exoscale.rpc.authorizer.v1.TLSNameR\asubject\x129\n" +
	"\n" +
	"not_before\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tnotBefore\x127\n" +
	"\tnot_after\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\bnotAfter\x12\x13\n" +
	"\x05is_ca\x18\a \x01(\bR\x04isCa\x12\x1b\n" +
	"\tdns_names\x18\b \x03(\tR\bdnsNames\x12'\n" +
	"\x0femail_addresses\x18\t \x03(\tR\x0eemailAddresses\x12!\n" +
	"\fip_addresses\x18\n" +
	" \x03(\tR\vipAddresses\x12\x12\n" +
	"\x04uris\x18\v \x03(\tR\x04uris\"\xbe\x02\n" +
	"\aTLSName\x12\x18\n" +
	"\acountry\x18\x01 \x03(\tR\acountry\x12\"\n" +
	"\forganization\x18\x02 \x03(\tR\forganization\x12/\n" +
	"\x13organizational_unit\x18\x03 \x03(\tR\x12organizationalUnit\x12\x1a\n" +
	"\blocality\x18\x04 \x03(\tR\blocality\x12\x1a\n" +
	"\bprovince\x18\x05 \x03(\tR\bprovince\x12%\n" +
	"\x0estreet_address\x18\x06 \x03(\tR\rstreetAddress\x12\x1f\n" +
	"\vpostal_code\x18\a \x03(\tR\n" +
	"postalCode\x12#\n" +
	"\rserial_number\x18\b \x01(\tR\fserialNumber\x12\x1f\n" +
	"\vcommon_name\x18\t \x01(\tR\n" +
	"commonName\"\x95\x02\n" +
	"\x03JWT\x12\x18\n" +
	"\asubject\x18\x01 \x01(\tR\asubject\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12%\n" +
	"\x0eemail_verified\x18\x03 \x01(\bR\remailVerified\x12\x16\n" +
	"\x06groups\x18\x04 \x03(\tR\x06groups\x12\x16\n" +
	"\x06issuer\x18\x05 \x01(\tR\x06issuer\x12\x1a\n" +
	"\baudience\x18\x06 \x03(\tR\baudience\x127\n" +
	"\tissued_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\bissuedAt\x122\n" +
	"\x06expiry\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\x06expiry\"$\n" +
	"\fHeaderValues\x12\x14\n" +
	"\x05value\x18\x01 \x03(\tR\x05value\"\xdb\x02\n" +
	"\vGrpcRequest\x12\x18\n" +
	"\aservice\x18\x01 \x01(\tR\aservice\x12\x16\n" +
	"\x06method\x18\x02 \x01(\tR\x06method\x12N\n" +
	"\aheaders\x18\x03 \x03(\v24.exoscale.rpc.authorizer.v1.GrpcRequest.HeadersEntryR\aheaders\x121\n" +
	"\x03tls\x18\x04 \x01(\v2\x1f.exoscale.rpc.authorizer.v1.TLSR\x03tls\x121\n" +
	"\x03jwt\x18\x05 \x01(\v2\x1f.exoscale.rpc.authorizer.v1.JWTR\x03jwt\x1ad\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12>\n" +
	"\x05value\x18\x02 \x01(\v2(.exoscale.rpc.authorizer.v1.HeaderValuesR\x05value:\x028\x01\"\xe8\x03\n" +
	"\vHttpRequest\x12\x1f\n" +
	"\vhttp_method\x18\x01 \x01(\tR\n" +
	"httpMethod\x12N\n" +
	"\aheaders\x18\x02 \x03(\v24.exoscale.rpc.authorizer.v1.HttpRequest.HeadersEntryR\aheaders\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\x12\x12\n" +
	"\x04host\x18\x04 \x01(\tR\x04host\x12\x16\n" +
	"\x06scheme\x18\x05 \x01(\tR\x06scheme\x12\x14\n" +
	"\x05query\x18\x06 \x01(\tR\x05query\x12\x12\n" +
	"\x04size\x18\a \x01(\x03R\x04size\x12\x1a\n" +
	"\bprotocol\x18\b \x01(\tR\bprotocol\x121\n" +
	"\x03tls\x18\t \x01(\v2\x1f.exoscale.rpc.authorizer.v1.TLSR\x03tls\x121\n" +
	"\x03jwt\x18\n" +
	" \x01(\v2\x1f.exoscale.rpc.authorizer.v1.JWTR\x03jwt\x12\x16\n" +
	"\x06method\x18\v \x01(\tR\x06method\x1ad\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12>\n" +
	"\x05value\x18\x02 \x01(\v2(.exoscale.rpc.authorizer.v1.HeaderValuesR\x05value:\x028\x01B2Z0github.com/exoscale/stelling/fxauthorizer/schemab\x06proto3"

var (
	file_schema_proto_rawDescOnce sync.Once
	file_schema_proto_rawDescData []byte
)

func file_schema_proto_rawDescGZIP() []byte {
	file_schema_proto_rawDescOnce.Do(func() {
		file_schema_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_schema_proto_rawDesc), len(file_schema_proto_rawDesc)))
	})
	return file_schema_proto_rawDescData
}

var file_schema_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_schema_proto_goTypes = []any{
	(*TLS)(nil),                   // 0: exoscale.rpc.authorizer.v1.TLS
	(*TLSName)(nil),               // 1: exoscale.rpc.authorizer.v1.TLSName
	(*JWT)(nil),                   // 2: exoscale.rpc.authorizer.v1.JWT
	(*HeaderValues)(nil),          // 3: exoscale.rpc.authorizer.v1.HeaderValues
	(*GrpcRequest)(nil),           // 4: exoscale.rpc.authorizer.v1.GrpcRequest
	(*HttpRequest)(nil),           // 5: exoscale.rpc.authorizer.v1.HttpRequest
	nil,                           // 6: exoscale.rpc.authorizer.v1.GrpcRequest.HeadersEntry
	nil,                           // 7: exoscale.rpc.authorizer.v1.HttpRequest.HeadersEntry
	(*timestamppb.Timestamp)(nil), // 8: google.protobuf.Timestamp
}
var file_schema_proto_depIdxs = []int32{
	1,  // 0: exoscale.rpc.authorizer.v1.TLS.issuer:type_name -> exoscale.rpc.authorizer.v1.TLSName
	1,  // 1: exoscale.rpc.authorizer.v1.TLS.subject:type_name -> exoscale.rpc.authorizer.v1.TLSName
	8,  // 2: exoscale.rpc.authorizer.v1.TLS.not_before:type_name -> google.protobuf.Timestamp
	8,  // 3: exoscale.rpc.authorizer.v1.TLS.not_after:type_name -> google.protobuf.Timestamp
	8,  // 4: exoscale.rpc.authorizer.v1.JWT.issued_at:type_name -> google.protobuf.Timestamp
	8,  // 5: exoscale.rpc.authorizer.v1.JWT.expiry:type_name -> google.protobuf.Timestamp
	6,  // 6: exoscale.rpc.authorizer.v1.GrpcRequest.headers:type_name -> exoscale.rpc.authorizer.v1.GrpcRequest.HeadersEntry
	0,  // 7: exoscale.rpc.authorizer.v1.GrpcRequest.tls:type_name -> exoscale.rpc.authorizer.v1.TLS
	2,  // 8: exoscale.rpc.authorizer.v1.GrpcRequest.jwt:type_name -> exoscale.rpc.authorizer.v1.JWT
	7,  // 9: exoscale.rpc.authorizer.v1.HttpRequest.headers:type_name -> exoscale.rpc.authorizer.v1.HttpRequest.HeadersEntry
	0,  // 10: exoscale.rpc.authorizer.v1.HttpRequest.tls:type_name -> exoscale.rpc.authorizer.v1.TLS
	2,  // 11: exoscale.rpc.authorizer.v1.HttpRequest.jwt:type_name -> exoscale.rpc.authorizer.v1.JWT
	3,  // 12: exoscale.rpc.authorizer.v1.GrpcRequest.HeadersEntry.value:type_name -> exoscale.rpc.authorizer.v1.HeaderValues
	3,  // 13: exoscale.rpc.authorizer.v1.HttpRequest.HeadersEntry.value:type_name -> exoscale.rpc.authorizer.v1.HeaderValues
	14, // [14:14] is the sub-list for method output_type
	14, // [14:14] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_schema_proto_init() }
func file_schema_proto_init() {
	if File_schema_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_schema_proto_rawDesc), len(file_schema_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_schema_proto_goTypes,
		DependencyIndexes: file_schema_proto_depIdxs,
		MessageInfos:      file_schema_proto_msgTypes,
	}.Build()
	File_schema_proto = out.File
	file_schema_proto_goTypes = nil
	file_schema_proto_depIdxs = nil
}
