---
name: Earthly
description: Run an earthly target

inputs:
  target:
    description: 'The earthly target to run'
    required: true
    default: +ci

runs:
  using: composite
  steps:
    - uses: earthly/actions-setup@v1
      with:
        github-token: ${{ github.token }}
        use-cache: true
    - name: earthly
      shell: bash
      env:
        FORCE_COLOR: "1" # Force earthly to use color output
      run: |
        earthly \
        --ci \
        --allow-privileged \
        --github-annotations \
        ${{ inputs.target }}
