name: Example CI pipeline

# --- Earthly workflows ---
# For more information on our shared Earthly workflows, see:
# - https://github.com/exoscale/github-actions
# - https://github.com/exoscale/earthly-action

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  # Format and fix code
  format:
    uses: exoscale/github-actions/.github/workflows/earthly-format.yaml@shillaker/chore/add-working-dir-to-earthly-action
    secrets: inherit
    with:
      target: +format-lint-fix
      working-directory: examples

  # Check for drift in codegen
  drift:
    uses: exoscale/github-actions/.github/workflows/earthly-drift.yaml@shillaker/chore/add-working-dir-to-earthly-action
    secrets: inherit
    with:
      target: +gen
      working-directory: examples

  # Work out version
  version:
    runs-on: exo-arc-exoscale-runner
    outputs:
      version: ${{ steps.tag.outputs.version }}
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0
      - name: Compute version from commit count
        id: tag
        shell: bash
        run: echo "version=1.0.$(git rev-list --count HEAD)" >> "$GITHUB_OUTPUT"

  # Run CI pipeline
  pipeline:
    needs: [format, drift, version]
    uses: exoscale/github-actions/.github/workflows/earthly.yaml@shillaker/chore/add-working-dir-to-earthly-action
    secrets: inherit
    with:
      target: +pipeline-ci
      working-directory: examples
      tag-strategy: |
        type=raw,value=${{ needs.version.outputs.version }},enable=${{ github.ref == format('refs/heads/{0}', github.event.repository.default_branch) }}
        type=sha,prefix=,format=long,enable=true
