name: Example CI pipeline

on:
  push:
    branches: [ master, main ]
  pull_request:

jobs:
  format:
    uses: ./.github/workflows/earthly-format.yaml
    with:
      target: ./examples+format

  vulncheck:
    uses: ./.github/workflows/earthly.yaml
    with:
      target: ./examples+vulncheck

  pipeline:
    uses: ./.github/workflows/earthly.yaml
    with:
      target: ./examples+ci
